// "use client";

import './globals.css';
import theme from './theme';
import styles from './layout.module.scss';
import type { Metadata } from 'next';

import NavBar from 'src/components/NavBar';
import { Providers } from './Providers';

export const metadata: Metadata = {
  title: 'WHO',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Providers>
          <NavBar></NavBar>
          <main className={styles.main}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
